name: Build APK

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install Buildozer and dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git
          pip install buildozer
          sudo apt install -y openjdk-11-jdk  # Ensure Java is installed

      - name: Build APK
        run: |
          buildozer -v android debug  # Remove cd command

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: myapp-debug.apk
          path: bin/*.apk  # Adjust if your APK is named differently
