name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
          echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))" >> $GITHUB_ENV

      - name: Install Android SDK
        run: |
          sudo apt update
          sudo apt install -y android-sdk
          echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools" >> $GITHUB_ENV

      - name: Install Android Command Line Tools
        run: |
          sudo apt install -y android-sdk-commandlinetools
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Install Buildozer and dependencies
        run: |
          sudo apt install -y python3-pip git
          pip install buildozer cython opencv-python numpy

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: myapp-debug.apk
          path: bin/*.apk
